### ISSUE TITLE
Error The operation couldn’t be completed. (NIO.NIOConnectionError error 1.)

### ISSUE THREAD

**Issue by schmidarnold** [swift-server/async-http-client#149]
If I try to create a connection as shown in the doku  I get the above error: 
```
var request = try HTTPClient.Request(url: "https://swift.org", method: .GET)

//request.headers.add(name: "Authorization: \(authorizationHeader.description)" , value: "")
//print (request.headers.description)
httpClient.execute(request: request).whenComplete { result in
    switch result {
    case .failure(let error):
        print (error.localizedDescription)
    case .success(let response):
        if response.status == .ok {
            print (response.status)
        } else {
            print ("error in response")
        }
    }
}
```
Arnold

**Comment by weissi** [comment]
CC @artemredkin

**Comment by artemredkin** [comment]
Hi, here what's happening. When you call `execute` method you get a `EventLoopFuture` of the response. Then, you add a callback to this future that will be executed at some point in time, but then your program continues to run and de-allocates the client and that in turn forces http client to close all connection, that in turn leads to your request being failed before it manages to succeed (side note: instead of printing `.localizedDescription`, try printing an error itself, then you will get much better error description). To fix that you need to guarantee that client will be alive until http request has time to complete. One simple way to do it is to call `.wait()` on the future you get from `.execute`, but that is only good for testing/demo purposes, as it will block the thread its called on. Usually, http client is created for the duration of an application life and until this application is alive, requests will be executed and your callback will be called.

@weissi do you think this should be clarified in the readme?

**Comment by schmidarnold** [comment]
Thanks, now its clear. But I want to use it in a server side cron job, so its a command line prog.Therefore I have to work in an synchronous mannier( sequential). Ok then I try it to call with wait(). Perhaps you can tell me please (I see you know very well the library) how I can create a header for my digest authentication like ("Authorization: Digest bla..bla"). I didn't found the possibility to create a simple header without name and value....
Thank you for you immediate response.

**Comment by artemredkin** [comment]
Sure, to add a header named `Authorization` with value `Digest: xxx` you can do the following:
```
var request = try HTTPClient.Request(url: "https://swift.org", method: .GET)
request.headers.add(name: "Authorization", value: "Digest xxx")
```

**Comment by weissi** [comment]
@artemredkin yeah, I think clarifying this would be a great idea

**Comment by schmidarnold** [comment]
I will try it. I used your form in my previous attempts, but there I had problems with the error describe above, but it should be resolve now. Now I can retry my authentication steps. I use as described in the doku a delegate to create my authorizationheader in the didreceivehead function of my delegate. But then I have to send it back to server server. I will try also your propose of the header but in the dokus of Digest Authentication the response of the client shoud be in the form:
```
Authorization: Digest username="Mufasa",
                     realm="testrealm@host.com",
                     nonce="dcd98b7102dd2f0e8b11d0f600bfb0c093",
                     uri="/dir/index.html",
                     qop=auth,
                     nc=00000001,
                     cnonce="0a4f113b",
                     response="6629fae49393a05397450978507c4ef1",
                     opaque="5ccc069c403ebaf9f0171e9517f40e41" 
```
If I am able to create a digest authentication against the remote server using async-http-client I will give you surely a feedback. 
Thank you for your hints and tipps.
