### ISSUE TITLE
Return the response HTTP version to the user

### ISSUE THREAD

**Issue by grosch** [swift-server/async-http-client#164]
https://github.com/swift-server/async-http-client/blob/e2636a4c24e646d3e480fc666da0c090818beb09/Sources/AsyncHTTPClient/HTTPHandler.swift#L656

Why is this hardcoding 1.1?  There are still severs that return 1.0, and when doing caching it's important to know whether it's a 1.0 or 1.1 type reply because that changes what you send back in to do validation.

**Comment by Lukasa** [comment]
Because we only emit HTTP/1.1 requests, regardless of what the server responds with.

**Comment by grosch** [comment]
So I'm probably looking in the wrong area then.  I'm trying to find out what version the server responded with.

@tanner0101

**Comment by tanner0101** [comment]
The HTTP version struct is indeed not passed along in the response either: https://github.com/swift-server/async-http-client/blob/master/Sources/AsyncHTTPClient/HTTPHandler.swift#L343-L346

I assume this is because it wouldn't make sense for a server to respond with 1.0 when a 1.1 request was sent. But I don't have an RFC reference to back that claim up.

**Comment by Lukasa** [comment]
Servers are free to respond with a 1.0 response to a 1.1 request. This seems like something we should communicate back to the user.
