### ISSUE TITLE
How can i upload file use multipart/form-data?

### ISSUE THREAD

**Issue by Adrift001** [swift-server/async-http-client#287]

**Comment by tanner0101** [comment]
This package doesn't have any helpers for parsing / serializing multipart. You'll need to do that manually or use another package. 

Vapor 4 includes a multipart parser and serializer as well as Encoder / Decoder implementations for multipart/form-data
https://github.com/vapor/vapor/tree/master/Sources/Vapor/Multipart

If you just need to serialize multipart, that's relatively easy: https://github.com/vapor/vapor/blob/master/Sources/Vapor/Multipart/MultipartSerializer.swift is less than 50 lines. 

Parsing is more complexing, especially if you want to support streaming. Vapor's multipart parser is based off this C implementation: https://github.com/vapor/vapor/tree/master/Sources/CMultipartParser

Closing this issue since it's not a feature request or bug (and multipart is outside of the scope of this library anyway). I'm happy to answer any additional questions though.

**Comment by Adrift001** [comment]
So i need import Vapor package?

**Comment by tanner0101** [comment]
@Adrift001 that would work. Here's an example using `Vapor` (which uses async-http-client under the hood):

```swift
import Vapor

var env = try Environment.detect()
try LoggingSystem.bootstrap(from: &env)

let app = Application(env)
defer { app.shutdown() }

struct Test: Content {
    var name: String
    var file: File
}
let test = Test(
    name: "vapor",
    file: .init(data: String(repeating: "a", count: 5_000), filename: "a.txt")
)
let res = try app.client.post("https://httpbin.org/post") { req in
    try req.content.encode(test, as: .formData)
}.wait()
print(res)
```

Vapor is an entire web framework though so it's kind of a heavy dependency to bring in for just a client. Eventually I'd like to split out the multipart / form-data stuff into a separate package for use with async-http-client standalone. Haven't had time yet though.

**Comment by Adrift001** [comment]
Thanks!
