### ISSUE TITLE
HTTPClient.syncShutdown() check currentEventLoop is not nil doesn't work on NIOTS

### ISSUE THREAD

**Issue by adam-fowler** [swift-server/async-http-client#300]
This produces differing results between macOS and Linux

**Comment by Lukasa** [comment]
Check on current event loops on NIOTS must be willing to tolerate false negatives. If they are intended to be assertions, they should use the appropriate assert primitives.

**Comment by Lukasa** [comment]
However, the check in question uses `currentEventLoop`. This functionality cannot be implemented on NIOTS: it is not possible to ask what event loop you’re on. The check as provided literally cannot be duplicated, and so I think this is NTBF.

**Comment by adam-fowler** [comment]
@Lukasa is there any way for `syncShutdown` to check if we are running on an EventLoop when using NIOTS?

**Comment by Lukasa** [comment]
No, Dispatch provides no way to check if you are on a DispatchQueue (because the question makes no sense in the Dispatch model). The only way to make this solution 100% bulletproof is to keep a registry of all EventLoops in the program, and as EventLoop supports arbitrary conforming types we can’t even guarantee to do that.

**Comment by adam-fowler** [comment]
Ok I guess this Issue is going nowhere. Should I close?

**Comment by Lukasa** [comment]
Sorry we can’t do any better here!
