### ISSUE TITLE
Fatal error if server responds with Payload Too Large during upload streaming

### ISSUE THREAD

**Issue by t089** [swift-server/async-http-client#49]
I've been playing with implementing a "max body size" policy in my NIO based web-server and noticed that this can trigger a `fatalError` in the state machine of `ResponseAccumulator`.

You can reproduce this as follows:

In `HttpBinHandler` change the `.body` handler to:

```swift
var response = self.resps.removeFirst()
guard response.body?.readableBytes ?? 0 < self.maxBodySize else {
    context.close(mode: .input).whenSuccess {
        context.write(self.wrapOutboundOut(.head(HTTPResponseHead(version: HTTPVersion(major: 1, minor: 1), status: .payloadTooLarge))), promise: nil)
        context.writeAndFlush(self.wrapOutboundOut(.end(nil)), promise: nil)
    }
    self.resps.prepend(response)
    return
}
response.add(body)
self.resps.prepend(response)
```

Here `self.maxBodySize` is a constant `let maxBodySize: Int = 1_024 * 1_024 // 1 MB`.

When the server receives more than the allowed body size it will close the input stream and send a `payloadTooLarge` response to the client. Not sure if this is the correct way to implement this, though?!?

Anyhow, with this change this test case will trigger a `fatalError`:

```swift
func testUploadStreamingTooMuch() throws {
    let httpBin = HttpBin()
    let httpClient = HTTPClient(eventLoopGroupProvider: .createNew)
    defer {
        try! httpClient.syncShutdown()
        httpBin.shutdown()
    }
    
    let body: HTTPClient.Body = .stream(length: nil) { writer in
        var bytesWritten: Int = 0
        let chunkSize = 1_024 * 100
        let totalSize = 1_024 * 1_024 * 10
        var buffer = ByteBufferAllocator().buffer(capacity: chunkSize)
        buffer.writeBytes([UInt8](repeating: 0, count: chunkSize))
        func step() -> EventLoopFuture<Void> {
            let f = writer.write(.byteBuffer(buffer))
            let eventLoop = f.eventLoop
            return f.flatMap {
                print("Uploaded: \(bytesWritten) / \(totalSize) (\(round(Float(bytesWritten) / Float(totalSize) * 1000) / 10)%)")
                bytesWritten += chunkSize
                if bytesWritten < totalSize {
                    return step()
                } else {
                    return eventLoop.makeSucceededFuture(())
                }
            }
        }
        
        return step()
    }
    
    var request = try Request(url: "http://localhost:\(httpBin.port)/post")
    request.method = .POST
    request.headers.add(name: "Transfer-Encoding", value: "chunked")
    request.body = body
    let response = try httpClient.execute(request: request).wait()
    let bytes = response.body.flatMap { $0.getData(at: 0, length: $0.readableBytes) }
    
    
    XCTAssertEqual(.payloadTooLarge, response.status)
    XCTAssertNil(bytes)
}
```

```
Fatal error: head already set: file /Users/tobias/Developing/swift-nio-http-client/Sources/NIOHTTPClient/HTTPHandler.swift, line 145
2019-06-24 09:43:23.371626+0200 xctest[99350:18225045] Fatal error: head already set: file /Users/tobias/Developing/swift-nio-http-client/Sources/NIOHTTPClient/HTTPHandler.swift, line 145
```

The reason for this is, that the server will actually send a second `Bad Request` response to the client. This response comes from the `HTTPServerProtocolErrorHandler` which receives a `invalidEOFState` error and translates this into a `Bad Response` error.

So I guess this might also indicate that the way I've implemented the max body size policy might be wrong if this leads to a protocol error?

You can check out a branch with the changes here: https://github.com/t089/swift-nio-http-client/tree/maxBodysize

**Comment by Lukasa** [comment]
The server MUST NOT send a response head if it has already sent one, as it leads to an inevitable protocol error. In this case, if you've inserted `HTTPServerProtocolErrorHandler` into the pipeline you should *either* let it send the 400, or not throw an error, but not both.

**Comment by t089** [comment]
Hm, I don't think I understand. I don't want to send a `400`, I want to terminate the client upload and send a `413`. How would I do this then correctly?

**Comment by Lukasa** [comment]
Ah, I see, this is a bunch of things all at once.

When you close the input, the effect of doing this is to immediately trigger a HTTP framing violation. This violation is reported by the `HTTPDecoder` and spotted by the `HTTPServerProtocolErrorHandler`, which triggers a 400. You then subsequently attempt to send a 413.

There are a few ways around this. The first way is basically just working around the error handler logic: you can write the 413 `.head`, then close the input, then write the 413 `.end`. The error handler will not send a 400 response if it believes there's already a partial response on the wire, so that will be prevented.

However, the better thing is to not call `.close(.input)`. `.close(.input)` is a bad call, and I frankly wish we'd never implemented it: it simply makes no sense. Other handlers do not spot that *we* chose to close the input ourselves, so they assume the remote peer did it. You're also then triggering a connection leak: you only close the input, not the output, so the file descriptor will be open forever.

A *better* choice is to write and flush the 413, and then just call `.close`. This does have the risk of dropping the 413 response in some cases, so if you're worried about that you could write the 413, call `close(.output)`, followed a second later by a full `close()` to drop the connection if you didn't get a `channelInactive`. This will also mean that while the 400 error will still get triggered, it won't get written to the channel.

Relatedly, swift-nio-http-client should not fatal error in this case: it should tolerate this.

**Comment by t089** [comment]
Ah thank you, this response filled a few blank spots in my understanding. Awesome.

**Comment by artemredkin** [comment]
Fixed by NIO patch: https://github.com/apple/swift-nio/pull/1093/files
